### PR TITLE
fix: add ability to pass function to method arg in save_results

### LINKED ISSUE #64: [Bug]: `method` argument in `save_results` seems to be unused
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

0.2.0

### Platform and OS Version

macOs 13.3.1

### Existing Issues

_No response_

### What happened?

In the [documentation](https://appsilon.github.io/data.validator/reference/save_results.html?q=save_re#null), it defines `method` argument as "Function that should be used to save results table (write.csv default)." However, it seems that method the argument is unused. (See code snippet below)

### Steps to reproduce

```
library(data.validator)

report <- data_validation_report()
report$save_results

[Output]
function (file_name, method = write.csv, ...) 
{
    self$get_validations(unnest = TRUE) %>% write.csv(file = file_name)
}
<environment: 0x10e109da8>
```

### Expected behavior

We should be able to define the write method using `method` argument in `save_results`.

### Attachments

_No response_

### Screenshots or Videos

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by anirbanshaw24**
### Link to the issue
Closes #64 

Before submitting a PR please answer:
* Was it necessary to update README? Is README updated?
No

* Are unit tests added for new logic?
Yes

### CODE REVIEW

File: R/report.R [hunk 1]
```diff
@@ -79,9 +79,17 @@ Report <- R6Class( #nolint: object_name_linter
       self$print(success, warning, error)
       sink()
     },
-    save_results = function(file_name, method = write.csv, ...) {
-      self$get_validations(unnest = TRUE) %>%
-        write.csv(file = file_name)
+    save_results = function(file_name = "results.csv", method = utils::write.csv, ...) {
+      func_args <- names(formals(method))
+      if (!any(func_args == "...") && !("file" %in% func_args))
```
Comment (jakubnowicki) [inline R/report.R:84]: This is a very limiting and weak approach. Moreover, it is not documented. It is ok to ask a user to provide a save method with some specified parameters but:
1. Why do you expect that `...` with `file` parameter?
2. Why you expect that the object that should be saved is going to be the first or the second parameter?
None of this is checked. And with this approach, you give no suggestion on how to deal with methods that have different parameters, e.g. `path` instead of `file`.

Suggested approach:
- remove the parameters evaluation part
- add documentation that will inform a user what are the required parameters for the method (follow the convention from `utils` and `readr` with `x` and `file`)
- add examples of how to deal with methods with different parameter names - create a wrapper that will change the names
- make sure that all arguments are passed to the method so instead of using pipe, call `method(x = , file = )`
- add information about the required parameters to the error message that is emitted if the writing method fails
- everything needs to be tested

**Review by jakubnowicki — CHANGES_REQUESTED** [review]
Please check comments. Also:
- bump package version
- update NEWS.md

File: R/report.R [hunk 2]
```diff
@@ -142,11 +141,22 @@ get_results <- function(report, unnest = FALSE) {
...
-  report$save_results(file_name, method, ...)
+  tryCatch({
+    report$save_results(file_name, method, ...)
+  },
+  error = function(error) {
+    rlang::abort(
+      "Method is not supported. Method must have 'x' and 'file' arguments.
+      Please create a wrapper function to use un-supported methods."
+    )
+  })
```
Comment (jakubnowicki) [inline R/report.R:159]: 1. `save_result` is just a facade function, the logic is in the R6 class method, thus it makes little sense to put the error handling here.
2. Saving can fail not only due to the problem with the method parameter names. The error message should a) include the original error message, so it is possible to debug the problem, b) only suggest that the problem might be in the names of parameters.

File: examples/save_results_methods/example.R [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+  validate_rows(description = "Each row sum for am:vs columns is less or equal 1",
+                rowSums, within_bounds(0, 1), vs:am) %>%
+  validate_cols(description = "For wt and qsec we have: abs(col) < 4 * sd(col)", within_n_sds(4), wt, qsec) %>%
+  validate_cols(description = "For wt and qsec we have: abs(col) < 2 * sd(col)", within_n_sds(2), wt, qsec) %>%
+  validate_rows(description = "Using mpg:carb mahalanobis distance for each observation is within 30 median absolute deviations from the median",
+                row_reduction_fn = maha_dist, within_n_mads(30), mpg:carb) %>%
+  validate_rows(description = "Using mpg:carb mahalanobis distance for each observation is within 3 median absolute deviations from the median",
+                row_reduction_fn = maha_dist, within_n_mads(3), mpg:carb) %>%
+  validate_if(description = "Column drat has only positive values", drat > 0) %>%
+  validate_if(description = "Column drat has only values larger than 3", drat > 3) %>%
```
Comment (jakubnowicki) [inline examples/save_results_methods/example.R:22]: This is overcomplicated. This example should show how to save results and focus on that.

File: examples/save_results_methods/example.R [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+  add_results(validator)
+
+get_results(validator)
+
+# We create a wrapper function for saveRDS.
```
Comment (jakubnowicki) [inline examples/save_results_methods/example.R:27]: Add information, why the wrapper is needed.

File: examples/save_results_methods/example.R [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+}
+save_results(validator, file_name = "results.rds", method = write_rds)
+
+# We create a wrapper function for save from base R.
+# Pass this function as method in `save_results`.
+base_save <- function(x, file, ...) {
+  save(x, file = file, ...)
+}
+save_results(validator, file_name = "results", method = base_save)
+
```
Comment (jakubnowicki) [inline examples/save_results_methods/example.R:40]: I miss an example of a function that does not need a wrapper.

File: tests/testthat/test-report.R [hunk 6]
```diff
@@ -38,6 +38,81 @@ test_that("exported CSV matched results obtained from get_results", {
...
+  expect_equal(actual, expected)
+})
+
+test_that("Error on passing a function without file argument", {
+  tmp <- file.path(tempdir(), "test.csv")
+  on.exit(unlink(tmp))
+
+  report <- report_test()
+  expect_error(save_results(report, tmp, method = utils::alarm))
+})
```
Comment (jakubnowicki) [inline tests/testthat/test-report.R:114]: The description should include the information on which function is being tested.

File: tests/testthat/test-report.R [hunk 7]
```diff
@@ -38,6 +38,81 @@ test_that("exported CSV matched results obtained from get_results", {
...
+  }
+)
+
+test_that("Fails when unsupported method is passed", {
+  tmp <- file.path(tempdir(), "test.csv")
+  on.exit(unlink(tmp))
+
+  report <- report_test()
+  expect_error(save_results(report, tmp, method = saveRDS))
+})
```
Comment (jakubnowicki) [inline tests/testthat/test-report.R:90]: How this is different from the last test?

**Review by jakubnowicki — CHANGES_REQUESTED** [review]
Please check my comments.

File: examples/save_results_methods/example.R (hunk 5 above)
Comment (anirbanshaw24) [reply examples/save_results_methods/example.R:40]: [This one ?](https://github.com/Appsilon/data.validator/blob/54aea11d6200bf73be35a3d72cbe08031c96eca4/tests/testthat/test-report.R#L92)

File: tests/testthat/test-report.R (hunk 7 above)
Comment (anirbanshaw24) [reply tests/testthat/test-report.R]: removed.

File: examples/save_results_methods/example.R (hunk 5 above)
Comment (jakubnowicki) [reply examples/save_results_methods/example.R:34]: Yes, can be a simple `write.csv`.

File: tests/testthat/test-report.R (hunk 6 above)
Comment (anirbanshaw24) [reply tests/testthat/test-report.R]: Changed

File: examples/save_results_methods/example.R (hunk 5 above)
Comment (jakubnowicki) [reply examples/save_results_methods/example.R:34]: Please add this example to this file. It should include a complete set of options.

**Review by jakubnowicki — APPROVED** [review]
LGTM
