### PR TITLE
Fix/no columns selected

### LINKED ISSUE #41: [Bug]: Validation without column names produces a report with failed validation
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

_No response_

### Platform and OS Version

_No response_

### Existing Issues

_No response_

### What happened?

When using the `validate_cols` without supplying any column name, no warning or error is being issued. The validation report looks as follows:
```
Validation summary: 
 Number of successful validations: 0
 Number of failed validations: 1
 Number of validations with warnings: 0

Advanced view: 


|table_name |description                                                    |type  | total_violations|
|:----------|:--------------------------------------------------------------|:-----|----------------:|
|mtcars     |There should not be any NAs or other missing values in columns |error |                1|
```
Even though there are not any NA values in the `mtcars` dataset, the report suggests there was one failed validation.

### Steps to reproduce

```
library(data.validator)
data("mtcars")
report_mtcars <- data_validation_report()
validate(mtcars, description = "Verifying cars dataset") %>%
  validate_cols(description = "There aren't any NAs in the dataset", not_na) %>%
  add_results(report_mtcars)
```

### Expected behavior

I expected the code to not produce a *failed validation*. I expected an empty report and a warning stating that I haven't chosen any columns or a report for all the columns.

### Attachments

_No response_

### Screenshots or Videos

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jakubnowicki**
Closes #41 

If no columns provided, the validation function will use all columns.

### CODE REVIEW

File: R/assertions.R [hunk 1]
```diff
@@ -162,18 +165,34 @@ validate_cols <- function(data,
...
-    ...,
-    skip_chain_opts = skip_chain_opts,
-    obligatory = obligatory,
-    description = description,
-    success_fun = success_fun,
-    error_fun = error_fun,
-    defect_fun = defect_fun
-  ) %>%
-    check_assertr_expression(data, description, error_fun)
+  assertion_command <- if (is.null(match.call(expand.dots = FALSE)$`...`)) {
```
Comment (mdubel) [inline R/assertions.R:168]: I don't like this part of code. I see that it can be improved on 3 levels, sorted with the increasing complexity of change:
1. How about moving `if` to the next line? It is hard to read right now.
2. We should extract the check to the separate variable with a meaningful name of what we are checking. For example:
```
is_colums_empty <- is.null(match.call(expand.dots = FALSE)$`...`)
assertion_command <- if(is_colums_empty) {
...
} else {
...
}
``` 
3. Maybe we could just have the columns selection in `if` clause, and have single call of the whole `assertr_function`? It might not be trivial to pass arguments correctly, so would require a bit work, up to you whether worth it.

File: R/assertions.R [hunk 2]
```diff
@@ -213,7 +233,22 @@ validate_rows <- function(data,
     list(direct = assertr::assert_rows, generator = assertr::insist_rows)
   )
 
-  assertr_function(
+  assertion_command <- if (is.null(match.call(expand.dots = FALSE)$`...`)) {
```
Comment (mdubel) [inline R/assertions.R:236]: I see that same comment applies here.

**Review by mdubel — COMMENTED** [review]
Code organisation comments added.

File: R/assertions.R (hunk 1 above)
Comment (jakubnowicki) [reply R/assertions.R:168]: 1. As we talked about, with nr 2 in place, this is not necessary.
2. Sounds ok
3. I was thinking about this, but ultimately, I decided to use the large if statement.  An attempt to pass just  `...`/`everything()` would overcomplicate the code.

**Review by mdubel — APPROVED** [review]
